version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /services/forumline-web
    schedule:
      interval: weekly
    groups:
      forumline-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
