services:
  forum:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.go-forum
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - PORT=3000

  forumline:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.go-forumline
      args:
        GITHUB_PACKAGES_TOKEN: ${GITHUB_PACKAGES_TOKEN}
    ports:
      - "3001:3000"
    env_file:
      - services/forumline-web/.env.local
    environment:
      - PORT=3000
